### PR TITLE
fix missing button

### PR DESCRIPTION
**Pull request by eddieduro**

### CODE REVIEW

**Comment by patternandshape** [comment]
having the worst time trying to view this on my laptop with our current readme instructions! if you get a minute sometime soon can you update the readme so it's easier to install? my terminal won't even recognize the first instruction I type in haha. Thanks!! Was super fun!

**Comment by eddieduro** [comment]
Hey Molly, I updated the README, hopefully the instructions were a little more clear - you have to do a few different things when your are at home. Let me know if this works out!

**Comment by patternandshape** [comment]
thanks Eddie! I downloaded mamp and turned on the 'power' button  but when i type 'mysql -uroot -proot' in terminal , when in crate or any folder, it says 'command not found' .. then after that what is the 'mysql shell in terminal' and does the bash one just mean the regular terminal? sorry i've never had to go this deep in terminal before!

**Comment by yvonnapc** [comment]
Hey Molly!

The command for mysql when using MAMP at home is a little different, if you
run this line in the terminal it should work:
/Applications/MAMP/Library/bin/mysql --host=localhost -uroot -proot

After you run that line you will see "MySql>" instead of the usual "User
$", and that will be the mySql shell

-YC

**Comment by patternandshape** [comment]
Hey Yvonna! I feel like I need baby directions haha... not sure if I'm supposed to be in user or the crate file on my desktop when in terminal typing that but when I did (tried from both folders) it said "ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/Applications/MAMP/tmp/mysql/mysql.sock' (2)" ... Thanks for your help!

**Comment by yvonnapc** [comment]
​
 phpexample.mov
https://drive.google.com/file/d/0B3IstzW9wA58Z0FFUDRlLW5pSjA/view?usp=drive_web
​Here is a video of me opening our project just now, let me know if any of
it doesnt work for you.
There are a couple things we didn't tell you like changing the localhost in
the app.php file, sorry molly!!

Let me know how it goes!

**Comment by patternandshape** [comment]
Yvonna! I'm so grateful you made a video. thank you! but I'm sad because my terminal gets stuck at the beginning installing composer :( just says 'command not found' even if I try sudo...
blarg!

**Comment by eddieduro** [comment]
Hey Molly,  you can't do a composer install in the root directory of the project?

**Comment by patternandshape** [comment]
screen shot 2016-03-13 at 11 49 22 am

I think it doesn't like me ha

**Comment by tolentino3575** [comment]
Hey Molly is this the sudo you tried to run? You'll have to initially
install with this code first, and then after you should have the composer
command to run composer install.

[image: Inline image 1]
https://www.learnhowtoprogram.com/php/object-oriented-php/composer

If it doesn't work out bring your laptop tomorrow I can try to get it up
during lunch!

**Comment by eddieduro** [comment]
I got our group project up on heroku :) http://crate-app.herokuapp.com/

**Comment by patternandshape** [comment]
yayyyy! that's so rad! thanks Eddie :)

**Comment by patternandshape** [comment]
hey guys! just making portfolios fancy as we all are, I was just wondering if there's any easy way to have the images in this app link to the higher res images on discogs so we don't get the thumbnails blowing up and looking so pixelated? just on the gallery page, so like search and collection probably?  just wondering! still stoked on this one :)

**Comment by eddieduro** [comment]
@patternandshape Hey molly I'll take a look at the code and see if we can limit it to imgs of a certain size. I'm still super stoked on the project too, great work by everyone!

**Pull request merged**
